sudo: true
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

env:
  - POLYMER=2

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm -q i && npm i -q --no-save bower polymer-cli && bower -q i &&
      gulp lint version:check &&
      polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html &&
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
        wct --env saucelabs;
      else
        xvfb-run -s '-screen 0 1024x768x24' wct;
      fi &&
      if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
        wct --env saucelabs-cron;
      fi;
    fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
